eMemo/Models/ErrorViewModel.cs
using System;

namespace eMemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

eMemo/Models/InquiryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eMemo.Models
{
    public class InquiryViewModel
    {
        public string documentNo { get; set; }
        public string policyNo { get; set; }
        public string proposalNo { get; set; }
        public string ebaoMemoStatusID { get; set; }
        public string osMemo { get; set; }
        public string sending { get; set; }
        public string citizenID { get; set; }
        public string partyID { get; set; }
        public string customerName { get; set; }
        public string customerSurname { get; set; }
        public string agentCode { get; set; }
        public string agentName { get; set; }
        public string agentSurname { get; set; }
        public string agentUnit { get; set; }
        public string agentGroup { get; set; }
        public string transactionDateForm { get; set; }
        public string transactionDateTo { get; set; }
        public string transactionID { get; set; }
        public string policyName { get; set; }
        public string eBaoMemoStatusID { get; set; }
        public string ebaoMemoStatus { get; set; }
    }

    public class InquiryInformation
    {
        public int memoTransactionID { get; set; }
        public basicInformation basicInformation { get; set; }
        public memoDocumentInformation memoDocumentInformation { get; set; }
        public memoAmendmentInformation memoAmendmentInformation { get; set; }
        public List<memoDocumentHistory> memoDocumentHistory { get; set; }
    }
    public class basicInformation
    {
        public string policyNo { get; set; }
        public string proposalNo { get; set; }
        public string proposalDate { get; set; }
        public string policyStatus { get; set; }
        public string policyName { get; set; }
        public string citizenID { get; set; }
        public string mainPlan { get; set; }
        public string agentName { get; set; }
        public string unit { get; set; }
        public string group { get; set; }
        public string agentEmail { get; set; }
        public string agentPhoneNumber { get; set; }
        public string customerEmail { get; set; }
        public string customerPhoneNumber { get; set; }
        public string serviceAgentEmail { get; set; }
        public string serviceAgentPhoneNumber { get; set; }

    }
    public class memoDocumentInformation
    {
        public string ebaoDocumentNo { get; set; }
        public string transactionDate { get; set; }
        public string createdUser { get; set; }
        public string ebaoMemoStatus { get; set; }
        public string ebaoRelpliedUser { get; set; }
        public string ebaoRelpliedDate { get; set; }
    }
    public class memoAmendmentInformation
    {
        public List<document> documents { get; set; }
        public List<history> history { get; set; }
    }

    public class document
    {
        public int memoDetailID { get; set; }
        public int sequence { get; set; }
        public string memoCode { get; set; }
        public string memoDescription { get; set; }
        public string comment { get; set; }
        public string letterStatus { get; set; }
        public DateTime? replyDate { get; set; }
        public string replyBy { get; set; }
        public string source { get; set; }
    }
    public class history
    {
        public string sendTo { get; set; }
        public string description { get; set; }
        public string channel { get; set; }
        public string sendDate { get; set; }
        public string sendTime { get; set; }
        public string sendBy { get; set; }
        public string sendStatus { get; set; }
    }
    public class memoDocumentHistory
    {
        public int memoDocumentHistoryID { get; set; }
        public string documentNo { get; set; }
        public string transactionDate { get; set; }
        public int osMemo { get; set; }
        public string printedBy { get; set; }
    }
    public class status
    {
        public string code { get; set; }
        public string message { get; set; }
    }
}

eMemo/Controllers/HomeController.cs
using eMemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace eMemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

eMemo/Controllers/InquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using eMemo.Models;
using Microsoft.AspNetCore.Mvc;

namespace eMemo.Controllers
{
    public class InquiryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Information(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                InquiryInformation viewModel = new InquiryInformation();
                viewModel.memoTransactionID = Convert.ToInt32(id);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
}
}

eMemo/Controllers/MasterSetupController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eMemo.Controllers
{
    public class MasterSetupController : Controller
    {
   
        public IActionResult MemoMapping()
        {
            return View();
        }
        public IActionResult RuleManagement()
        {
            return View();
        }
        public IActionResult MailManagement()
        {
            return View();
        }
    }
}

eMemo/Controllers/PreparationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eMemo.Views.Home
{
    public class PreparationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Information(string id)
        {
            ViewBag.id = id;
            return View();
        }
    }
}

eMemo/Controllers/PrintReportController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eMemo.Controllers
{
    public class PrintReportController : Controller
    {
        public IActionResult PrintMemoLetterReport()
        {
            return View();
        }
        public IActionResult DaysAfterMemoPrintedReport()
        {
            return View();
        }
        public IActionResult SendingMemoReport()
        {
            return View();
        }
        public IActionResult PendingReport()
        {
            return View();
        }
        public IActionResult PendingSummaryReport()
        {
            return View();
        }
    }
}

eMemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">eMemo System</h1>
    
</div>

eMemo/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>eMemo</title>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.2/css/theme.bootstrap_4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/Login-Form-Dark.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        #blocker {
            position: fixed;
            display: none;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            opacity: .5;
            background-color: #000;
            z-index: 1000;
            overflow: auto;
        }

            #blocker div {
                position: absolute;
                border: 16px solid #f3f3f3;
                border-radius: 50%;
                top: 50%;
                left: 50%;
                border-top: 16px solid #3498db;
                width: 120px;
                height: 120px;
                -webkit-animation: spin 2s linear infinite; /* Safari */
                animation: spin 2s linear infinite;
            }

        /* Safari */
        @@-webkit-keyframes spin {
            0% {
                -webkit-transform: rotate(0deg);
            }

            100% {
                -webkit-transform: rotate(360deg);
            }
        }

        @@keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }
    </style>
</head>

<body>
    <div id="blocker">
        <div></div>
    </div>
    <section class="login-dark">
        <form style="max-width:420px;border-radius:20px">
            <h2 style="font-size: 24px; text-align: center; color: #6B9863">eMemo System Login</h2>
            <div class="illustration"><i class="icon ion-ios-locked-outline text-danger"></i></div>
            <div class="mb-3">
                <input id="Username" autocomplete="off" type="text" style="background:white;border: solid; border-color: #C6C6C6;border-radius:15px" class="form-control text-dark" placeholder="Username" />
            </div>
            <div class="mb-3">
                <input id="password" style="background: white;border: solid; border-color: #C6C6C6; border-radius: 15px" 
                       class="form-control text-dark" type="password" placeholder="Password" />
            </div>
            <div style="display:flex;align-items:center;justify-content: center;">
                <a href="/eMemo/Home/Index" type="button" style="color:black;font-weight:bold; margin-right: 10px; background-color: #ABAFDD" class="btn btn-secondary">Login</a>
                <button type="reset" style="color: black; font-weight: bold; background-color: #ABAFDD" class="btn btn-secondary btnConfirmModal">Clear</button>
            </div>
        </form>
    </section>
</body>
</html>

eMemo/Views/PrintReport/DaysAfterMemoPrintedReport.cshtml
@{
    ViewData["Title"] = "15 Days After Memo Printed Report";
}
<link rel="stylesheet" href="~/css/Shared.css" />
<div style="margin:20px;">
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">15 Days After Memo Printed Report</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">

                    <div class="row">
                        <div class="col d-flex flex-column text-primary label-text">
                            <p>Memo Printed Date <span class="text-danger">*</span></p>
                            <div class="input-group">
                                <input id="beginDateMemoPrinted" placeholder="dd/mm/yyyy" type="text"
                                    class="form-control text-input datepicker" autocomplete="off">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fa fa-calendar-alt fa-fw"></i></span>
                                </div>
                            </div>

                        </div>
                        <div class="col d-flex flex-column text-primary label-text">
                            <p>To Memo Printed Date</p>
                            <div class="input-group">
                                <input id="endDateMemoPrinted" placeholder="dd/mm/yyyy" type="text"
                                    class="form-control text-input datepicker" autocomplete="off">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fa fa-calendar-alt fa-fw"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-1 d-flex flex-column text-primary label-text">
                            <p>Aging</p>
                            <select id="ddlCondition" class="custom-select custom-select-sm">
                                <option value="true" selected="">Please Select</option>
                                <option value="<"><</option>
                                <option value=">">></option>
                                <option value="=">=</option>
                            </select>
                        </div>
                         <div class="col-1 d-flex flex-column text-primary label-text">
                             <p>Days</p>
                           <input type="number" min="0" value="0" class="form-control text-input" id="txtPrintedDay" oninput="this.value = Math.abs(this.value)">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <div>
                <button id="btnSearchDayAfterMemoPrintedPreview" class="btn btn-primary" style="margin:5px"
                    type="button">Preview Excel</button>
                <button id="btnClear" class="btn btn-secondary" style="margin:5px" type="button">Clear</button>
            </div>
        </div>
    </div>
    <div id="divSearchResult" class="card d-none" style="margin-top:50px">
        <div class="card-header">
            <h5 class="mb-0">Search Results of 15 Days After Memo Printed Report</h5>
        </div>
        <div class="card-body overflow-auto" style="height: 250px;">
        </div>
        <div id="divFooterButton" class="card-footer text-center">
            <button id="btnExportExcel" style="margin:5px" class="btn btn-info" type="button">Export Excel</button>
            <button id="btnPrint" style="margin:5px" class="btn btn-primary" type="button">Print</button>
        </div>
    </div>
</div>
<script src="~/jspage/module9_Share.js"></script>
<script src="~/jspage/module9_DaysAfterMemoPrintedReport.js"></script>

eMemo/Views/PrintReport/PendingReport.cshtml
@{
    ViewData["Title"] = "Pending Report";
}

<link rel="stylesheet" href="~/css/Shared.css" />

<div style="margin:20px;">
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">Pending Report</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">

                    <div class="row">
                        <div class="col-6 d-flex flex-column text-primary label-text">
                            <p>As of Date <span class="text-danger">*</span></p>
                            <div class="input-group">
                                <input id="asOfDate" placeholder="dd/mm/yyyy" type="text"
                                    class="form-control text-input datepicker" autocomplete="off">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fa fa-calendar-alt fa-fw"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 d-flex flex-column text-primary label-text">
                            <p>Product Category</p>
                            <select id="ddlProductCategory" class="custom-select custom-select-sm">
                                <option></option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <div>
                <button id="btnSearchPendingPreview" class="btn btn-primary" style="margin:5px" type="button">Preview
                    Excel</button>
                <button id="btnClear" class="btn btn-secondary" style="margin:5px" type="button">Clear</button>
            </div>
        </div>
    </div>
    <div id="divSearchResult" class="card d-none" style="margin-top:50px">
        <div class="card-header">
            <h5 class="mb-0">Search Results of Pending Report</h5>
        </div>
        <div class="card-body overflow-auto" style="height: 250px;">
        </div>
        <div id="divFooterButton" class="card-footer text-center">
            <button id="btnExportExcel" style="margin:5px" class="btn btn-info" type="button">Export Excel</button>
            <button id="btnPrint" style="margin:5px" class="btn btn-primary" type="button">Print</button>
        </div>
    </div>
</div>
<script src="~/jspage/module9_Share.js"></script>
<script src="~/jspage/module9_PendingReport.js"></script>

eMemo/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eMemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.0.0-beta3-web/css/all.min.css" />
    <script src="~/lib/fontawesome-free-6.0.0-beta3-web/js/all.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    @* <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" /> *@
    <link rel="stylesheet" href="~/lib/print/print.min.css" />
    <script src="~/lib/print/print.min.js"></script>
    <script src='~/lib/print/pdf-lib.min.js'></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    @* <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css"> *@
    <link rel="stylesheet" type="text/css" href="~/lib/dataTables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/dataTables/css/select.dataTables.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"
        integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css"
        integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />

    @* <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script> *@
    <script src="~/lib/dataTables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/dataTables/js/dataTables.select.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <link href="~/lib/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" />
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker-thai.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.th.js"></script>


    <script src="~/lib/moment/moment.min.js"></script>
    <style>
        .text-input {
            height: 33px !important;
            cursor: pointer;
        }

        p {
            margin-top: 1rem;
            margin-bottom: 0.2rem;
        }

        .card-header,
        .modal-header {
            background-color: #FAEDC7 !important;
        }

        .card-header,
        .modal-header h5 {
            color: #b92b00 !important;
        }

        table.dataTable thead {
            background-color: #CAEEBE !important;
        }

        .dataTables_wrapper {
            width: 100% !important
        }



        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

        .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #111;
            color: white;
            padding: 10px 15px;
            border: none;
        }

        .openbtn:hover {
            background-color: #444;
        }

        #main {
            transition: margin-left .5s;
            padding: 20px;
        }

        .menuMain {
            font-size: 23px !important;
        }

        .subMenu {
            font-size: large !important;
        }

        div.sticky {
            transition: 0.5s;
            position: absolute;
            top: 30px;
            left: 160px;
            font-size: 18px;
        }

        .topright {
            position: absolute;
            top: 30px;
            right: 40px;
            font-size: 18px;
        }
    </style>
</head>

<body>
    <div class="sticky" style="font-weight:bold" id="profile">
        <span class="navbar-brand text-success font-weight-bold">eMemo</span>
        <span>Welcome :</span>
        <span class="col-12" id="userName">
        </span>
        <span class="col-12">
            Office : Head Office
        </span>
        <span class="col-12 text-primary">
            Date : @(DateTime.Now.ToString("dd-MM-yyyy",new System.Globalization.CultureInfo("th-TH")))
        </span>

    </div>
    <div class="topright">
        <a id="logout" style="cursor:pointer" class="btn btn-outline-danger my-2 my-sm-0">
            Logout
            <ion-icon style="margin-bottom:-2px;" name="log-out-outline" class="text-danger"></ion-icon>
        </a>
    </div>

    <div id="mySidebar" class="sidebar" style=" padding-bottom: 50px;">

        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>


        <a class="menuMain" asp-controller="Home" asp-action="Index" id="menuHome" hidden>Home</a>
        <a class="menuMain" asp-controller="Preparation" asp-action="Index" id="menuPreparation" hidden>e-Memo
            Preparation</a>
        <a class="menuMain" asp-controller="Inquiry" asp-action="Index" id="menuInquiry" hidden>e-Memo Inquiry</a>
        <a class="menuMain dropdown-toggle" href="#masterSubmenu" data-toggle="collapse" aria-expanded="false"
            id="menuMaster" hidden>
            Master
            Setup
        </a>
        <ul class="collapse list-unstyled" id="masterSubmenu" style="padding-left:20px">
            <li>
                <a class="subMenu" asp-controller="MasterSetup" asp-action="MemoMapping">Memo Mapping Master Setup</a>
                <a class="subMenu" asp-controller="MasterSetup" asp-action="RuleManagement">
                    Rule Management Master
                    Setup
                </a>
                <a class="subMenu" asp-controller="MasterSetup" asp-action="MailManagement">E-Mail Management</a>
            </li>
        </ul>
        <a class="menuMain dropdown-toggle" href="#printSubmenu" data-toggle="collapse" aria-expanded="false"
            id="menuReports" hidden>Reports</a>
        <ul class="collapse list-unstyled" id="printSubmenu" style="padding-left:20px">
            <li>
                <a class="subMenu" asp-controller="PrintReport" asp-action="DaysAfterMemoPrintedReport">
                    15 Days After
                    Memo Printed Report
                </a>
                <a class="subMenu" asp-controller="PrintReport" asp-action="SendingMemoReport">Sending Memo Report</a>
                <a class="subMenu" asp-controller="PrintReport" asp-action="PendingReport">Pending Report</a>
                <a class="subMenu" asp-controller="PrintReport" asp-action="PendingSummaryReport">
                    Pending Summary
                    Report
                </a>


            </li>
        </ul>
        <a asp-controller="PrintReport" asp-action="PrintMemoLetterReport" id="memuPrintMemoLetterReport" hidden>Print
            Memo Letter</a>
    </div>

    <div id="main" style="font-size:0.8rem!important;">
        <button class="openbtn" onclick="openNav()">&#9776; </button>

        <div style=" padding-top: 50px;">
            @RenderBody()
        </div>

    </div>



    @RenderSection("Scripts", required: false)
</body>

</html>
<script>
    var authKey = localStorage.getItem("auth.token");

    $.ajaxSetup({
        beforeSend: function (xhr) {
            xhr.setRequestHeader('AuthorizationKey', authKey);
        },
        error: function (jqXHR, textStatus, errorThrown) {
            if (jqXHR.status == 401) {
                localStorage.clear();
                window.location.href = "https://smartlife.segroup.co.th/portalnew/Authen/Login"
            }
            else {
                console.log(errorThrown);
                console.log(jqXHR);
                console.log(textStatus);
            }
        }
    });
    $(document).ready(function () {
        var userData = localStorage.getItem("userData");
        if (userData == null) {
            if (authKey != null && authKey != "") {
                $.ajax({
                    type: "GET",
                    url: apiUrl + '/Authorization/VerifyToken',
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        localStorage.setItem("userData", JSON.stringify(data));
                        document.getElementById("userName").textContent = data.userItem.username;
                        renderMenu();
                    }
                });
            }
            else {
                localStorage.clear();
                window.location.href = "https://smartlife.segroup.co.th/portalnew/Authen/Login"
            }
        }
        else {
            var userObject = JSON.parse(userData);
            document.getElementById("userName").textContent = userObject.userItem.username;
            renderMenu();
        }

        window.setInterval(function () {
            localStorage.removeItem("userData");
        }, 600000);
    });

    const apiUrl = @Json.Serialize(@Configuration.GetSection("PotalUrls").GetSection("apiUrl").Value);

    $('#logout').on('click', function (e) {
        var authKey = localStorage.getItem("auth.token");
        $.ajax({
            type: "POST",
            url: "https://smartlife-proxy.segroup.co.th/portalecbrapi/api/account/logout",
            contentType: "application/json; charset=utf-8",
            headers: {
                'Authorization': "Bearer " + authKey
            },
            success: function (data) {
                localStorage.clear();
                window.location.href = "https://smartlife.segroup.co.th/portalnew/Authen/Login"
            }
        });

    });

    function openNav() {
        document.getElementById("mySidebar").style.width = "300px";
        document.getElementById("main").style.marginLeft = "300px";
        document.getElementById("profile").style.marginLeft = "300px";
    }

    /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
        document.getElementById("profile").style.marginLeft = "160px";
    }
    function renderMenu() {
        var menuData = JSON.parse(localStorage.getItem("userData"));
        if (menuData.userItem != null && menuData.userItem.users != null && menuData.userItem.users.applicationMenu != null) {

            var menuDataRole = menuData.userItem.users.applicationMenu;
            var roleName = menuData.userItem.users.roleName;
            var roleName = menuData.userItem.users.roleName;

            if (roleName == "Administrator") {
                localStorage.setItem("isAdministrator", true);
            } else {
                localStorage.setItem("isAdministrator", false);
            }


            for (var i = 0; i < menuDataRole.length; i++) {
                var inRole = menuDataRole[i].mainName;

                if (inRole == "Home") {
                    $("#menuHome").attr("hidden", false);
                } else if (inRole == "e-Memo Preparation") {
                    $("#menuPreparation").attr("hidden", false);
                } else if (inRole == "e-Memo Inquiry") {
                    $("#menuInquiry").attr("hidden", false);
                }
                else if (inRole == "Master Setup") {
                    $("#menuMaster").attr("hidden", false);
                }
                else if (inRole == "Reports") {
                    $("#menuReports").attr("hidden", false);
                }
                else if (inRole == "Print Memo Letter") {
                    $("#memuPrintMemoLetterReport").attr("hidden", false);
                }


            }
        }
    }
</script>